services:
  ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    depends_on:
      - db
    ports:
      - "22:22"
      - "443:443"
      - "4444:4444"
      - "8080:8080"
    volumes:
      - msf_data:/home/msfuser/.msf4
    privileged: true
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: msf
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
  msf_data:
    driver: local
